### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by drikonsete** [PabloPerezRodriguez/twitch-chat#11]
Hi, I wanted to comment on a few things. The first is that messages can be seen with / me, the second is that moderation things can be done from the chat itself, there are streamers that do not have double screens and it costs them more. Thank you very much for continuing to develop this mod!

**Comment by PabloPerezRodriguez** [comment]
I don't understand the /me thing. In-game chat moderation doesn't feel doable right now, because I would have to modify how the Minecraft chat works and I'm just not that smart

**Comment by drikonsete** [comment]
When the user puts /me and message the message doesn't appear in chat(if u don't know what it is I put here an Image)
![image](https://user-images.githubusercontent.com/71932366/94596840-0146e600-028d-11eb-8fd8-8f0faeed8fb7.png)

**Comment by PabloPerezRodriguez** [comment]
Ohh!! Now I get it, yeah, it's a bug, I'll try to fix it in the next release
