### ISSUE TITLE
[Feature] Option for no chat prefix?

### ISSUE THREAD

**Issue by OoLunar** [PabloPerezRodriguez/twitch-chat#15]
Hello!

I'm a small time mute Twitch streamer, and this mod seems perfect for me! I was going to use it to communicate between my hardcore world and Twitch chat, however I don't wish to prefix every message just to talk to them. Is there a way to send every message over?

**Comment by OoLunar** [comment]
Actually, it seems like this can be somewhat achieved, although it looks a tad weird.
![2021-03-13_16 09 58](https://user-images.githubusercontent.com/46751150/111051164-a9550380-8416-11eb-9531-78dfe962fdd6.png)
![2021-03-13_16 09 49](https://user-images.githubusercontent.com/46751150/111051166-aa863080-8416-11eb-974c-03846bc08a95.png)

**Comment by OoLunar** [comment]
After getting some of my friends to help me test, every message is prepended with my minecraft username. Again, I'm playing on a solo hardcore world. Is this a bug?

**Comment by PabloPerezRodriguez** [comment]
That looks like you've activated broadcasting. Could you check if you have? If not, it's a bug

**Comment by OoLunar** [comment]
I'm positive I have, however it's also 4am. I'll do another stream tomorrow and try again. However, could we also have an option to enable and watch a channel by default? When I exited and rejoined my world, I completely forgot to re-enable it. As you can imagine, chat wasn't too happy with me lol

**Comment by PabloPerezRodriguez** [comment]
Yeah, I could totally implement that. Just FYI, broadcasting isn't meant for streaming, it's just for you to be able to broadcast your Twitch chat to a server so that other people can see it without having the mod installed.

**Comment by OoLunar** [comment]
Ohhh, then I probably had it on. Should I try to disable it then?

**Comment by PabloPerezRodriguez** [comment]
Yes, that should fix your problem!

**Comment by OoLunar** [comment]
I'm so sorry, I completely forgot about this! Yes, doing `/twitch broadcast disable` fixes the issue. World-persistent settings would be great though! I'm looking forward to it!
