### ISSUE TITLE
Auto convert channel and user name

### ISSUE THREAD

**Issue by rhyvin** [PabloPerezRodriguez/twitch-chat#2]
If you change `this.channel = channel ` to `this.channel = channel.toLowerCase()`, it should simplify user interaction. The same could be done for username. I may have the implementation incorrect, however the idea should work. Hope this helps.

**Comment by PabloPerezRodriguez** [comment]
Definetly something I have to do! I am not able to code right now because I don't have my computer, but on Friday I'll definetly sort this. 

Thanks for the feedback!!

**Comment by PabloPerezRodriguez** [comment]
Turns out this wasn't solved, becuase even though I was setting this.channel and this.username to the correct value, I wasn't using them. 🤦🏻‍♂️
