### ISSUE TITLE
Cyrillic

### ISSUE THREAD

**Issue by Avenurt** [PabloPerezRodriguez/twitch-chat#3]
![image](https://user-images.githubusercontent.com/60001096/72609977-50373000-3937-11ea-860e-605ec7a8e462.png)

Help ;c

**Comment by PabloPerezRodriguez** [comment]
Hey, could you tell me what you're typing?

**Comment by Avenurt** [comment]
Does not support Russian letters

**Comment by PabloPerezRodriguez** [comment]
I mean what you wrote to get that character. I copypasted a bunch of Russian letters and it worked fine, so I don't know how to reproduce this.

**Comment by Avenurt** [comment]
I write any Russian letters :(

**Comment by Avenurt** [comment]
![image](https://user-images.githubusercontent.com/60001096/72664555-a4621300-3a10-11ea-9beb-fd5bf8f35bcc.png)

**Comment by PabloPerezRodriguez** [comment]
Are you using Minecraft 1.14 or Minecraft 1.15? And do you have Force Unicode Font enabled or not?

**Comment by Avenurt** [comment]
I use version 1.15 and everything is the same when using Force Unicode Font or not

**Comment by PabloPerezRodriguez** [comment]
You're using Windows right? It works on my macOS machine but not on my Windows one

**Comment by Avenurt** [comment]
Yes i use the window

**Comment by Avenurt** [comment]
:(

**Comment by PabloPerezRodriguez** [comment]
Fixed! Gonna push it in a little bit and you should see the fixed build on CurseForge following that
