### ISSUE TITLE
Not receiving messages

### ISSUE THREAD

**Issue by iMcFly** [PabloPerezRodriguez/twitch-chat#4]
Hi!

I'm able to enable the twitch chat and it shows that it connects, I can send a message to my Twitch chat using the prefix I set up (and have verified that works), but the chat itself does not appear in Minecraft. So I'm effectively able to send messages but not receive them.

**Comment by PabloPerezRodriguez** [comment]
Hey, which Minecraft version are you on? And you're on the latest mod version on CurseForge, b0.5.1, right?

**Comment by iMcFly** [comment]
Hey! Thanks for the support! Yes, I'm up to date on everything.

I'm running; 
- Minecraft 1.15.1
- twitchchat-b0.5.1
- Fabric Loader 0.7.5+build.178-1.15.1
- fabric-api-0.4.27+build.286-1.15
- modmenu-1.8.3+build.19

**Comment by PabloPerezRodriguez** [comment]
Could you keep the launcher console open while you run your game and send me a copy of the log (it should display any messages you receive and errors the mod runs into).

You can keep the launcher open by going to settings and clicking "Keep the Launcher open while games are running".

**Comment by iMcFly** [comment]
See attached. For context; I started up the game, connected to the world on my server, connected to the twitch chat and sent a test message both via the game and via twitch.tv. Then quit the game.
[latest.log](https://github.com/PabloPerezRodriguez/twitch-chat/files/4088841/latest.log)

**Comment by PabloPerezRodriguez** [comment]
I'm gonna be honest, I have no clue why your client is not receiving any messages. Could you try using [this build](https://drive.google.com/uc?export=download&id=127Z05JGElV68s46PoAsdvGR6XZyH21eH)?

**Comment by iMcFly** [comment]
Getting the same behaviour with the new build. So weird. The only thing that I can think of is that I'm on a Mac; I figure that shouldn't make any difference with it being Java but not sure if it's expecting any Windows-dependencies of some sort? (Not a software developer so no idea - shot in the dark).

**Comment by PabloPerezRodriguez** [comment]
Yeah, it's the same build, just added a little more console output when it receives messages, could you send me a log of that?

It should work on Windows, I've tried on my machine and it works, even though I don't know why it doesn't support Unicode (but it just doesn't on Windows)

**Comment by iMcFly** [comment]
Oh excellent! And sorry I didn't even think to send the
[latest.log](https://github.com/PabloPerezRodriguez/twitch-chat/files/4094430/latest.log).

java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)

**Comment by PabloPerezRodriguez** [comment]
Ok, I can't recreate your environment because Java 12 is no longer supported, could you upgrade to Java 13?

**Comment by iMcFly** [comment]
Sure!

Now on java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

Rebooted after installation. Issue persists. Here's the [latest.log](https://github.com/PabloPerezRodriguez/twitch-chat/files/4106771/latest.log)

**Comment by PabloPerezRodriguez** [comment]
I've noticed you have some other mods, I don't think my mod does something specific enough to make it non-compatible with any mods, but it's giving me enough of a headache as is, so, could you rename the mods to something like *.jar.disabled before running the test?

I want you to test [this build](https://drive.google.com/uc?export=download&id=10rs9ynslqJE2s_HjyiytawRxCuZ4sD_o), it logs a bunch more stuff (sometimes even three times...). But before you send the log file, make sure to remove your oauth key (you can find it by searching for "oauth:" with notepad, there should be three occurrences).

I'd also like you to send me your config.json file in .minecraft/config, make sure to remove your oauth key here as well.

**Comment by iMcFly** [comment]
Absolutely! I've done as requested and so now the only mods that are active are the Fabric API, Mod Menu, and your latest build.

Here's the [latest.log](https://github.com/PabloPerezRodriguez/twitch-chat/files/4113160/latest.log) with the oauth keys removed.

And this is the contents of my config.json file;

`{"channel":"AlastairMcFly","username":"AlastairMcFly","oauthKey":"oauth:[redacted]","prefix":":"}
`

**Comment by PabloPerezRodriguez** [comment]
Could you try on another channel? I've tested on your channel and it doesn't work for me either. I'm looking into why it doesn't work, though.

**Comment by PabloPerezRodriguez** [comment]
Ha! Catched the bug! When you send messages to channels (which you can do without joining them), Twitch doesn't care about cAsE, but when you want to join a channel (to listen to messages on it), it does care.
I had always tested with my Twitch channel, which for some reason worked fine with case, but yours doesn't.
Anyways, it now works. Gonna clean up the code a bit, push it to git and put it on CurseForge.

**Comment by PabloPerezRodriguez** [comment]
Before closing this, could you try using [this build](https://drive.google.com/uc?export=download&id=1z8py0HaiLRsC4tB9by5SdU1fZGrgWI1-)? Just to make sure it works before releasing on CurseForge. No need to send logs.

**Comment by iMcFly** [comment]
That latest build works! Nice bug catch. Thank you so much!!
