### ISSUE TITLE
1.14.4 Does not reflect twitch chat ingame

### ISSUE THREAD

**Issue by McSkinnerOG** [PabloPerezRodriguez/twitch-chat#5]
Hey your 1.14.4 version of the mod does not get messages ingame from the twitch chat but you can send messages to twitch from the ingame chat fine.

**Comment by PabloPerezRodriguez** [comment]
Which version of the mod are you using?

**Comment by PabloPerezRodriguez** [comment]
I'm going to close this issue because it's been 3 months and you haven't responded. If you are down to reply anytime just reopen it.

**Comment by PabloPerezRodriguez** [comment]
I'm going to close this issue because it's been 3 months and you haven't responded. If you are down to reply anytime just reopen it.
