### ISSUE TITLE
don't work with RTL languages.

### ISSUE THREAD

**Issue by MrAbdul1** [PabloPerezRodriguez/twitch-chat#6]
Hello , I loved the mod and I hope to fix this problem the language I'm using is Arabic and I also use an Arabic fix plugin in the server thank you.

**Comment by PabloPerezRodriguez** [comment]
It works for me. Could you send me a sample text which isn't working for you?
Is your problem while sending or receiving messages? Or both?
And does it work normally with minecraft, like if you write a normal chat message?

**Comment by PabloPerezRodriguez** [comment]
I'm going to close this issue because it's been a month and you haven't responded. If you are down to reply anytime just reopen it.
