### ISSUE TITLE
1.16.2 crash

### ISSUE THREAD

**Issue by BluCobalt** [PabloPerezRodriguez/twitch-chat#7]
Trying to configure the mod trough mod menu causes a crash.

full crash: [https://hastebin.com/awuzipicaj.sql](https://hastebin.com/awuzipicaj.sql)
I have the latest versions of fabric api and fabric loader.

**Comment by PabloPerezRodriguez** [comment]
Should be fixed on version 0.8.2b, reopen this if your issue persists

**Comment by BluCobalt** [comment]
can confirm that this fixes the crash. thanks!
